/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

#include "k_task.h"
#include "k_mem.h"
#include "stm32f401xe.h"

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));
extern task_t running_task;
extern TCB tasks[MAX_TASKS];


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

int _close(int file)
{
  (void)file;
  return -1;
}


int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

/**
 * @brief This function handles system calls trigger by SVC instruction
 *        SVC call numbers:
 *          0: kernelInit
 *          1: createTask
 *          2: kernelStart
 *          3: yield
 *          4: taskInfo
 *          5: getTID
 *          6: taskExit
 * @retval None
 */
void SVC_Handler_Main(unsigned int *svc_args) {
  // Extract SVC number
  unsigned int svc_number;
  int ret;
  svc_number = ((char*)svc_args[6])[-2];

  switch (svc_number) {
    // Kernel init
    case 0: {
      kernelInit();
      break;
    }
    // Create task
    case 1: {
      // Argument TCB from r0 on stack
      TCB *task = (TCB *)svc_args[0];
      ret = createTask(task);
      // retval to get popped back into r0
      svc_args[0] = ret;
      break;
    }
    case 2: {
      ret = startKernel();
      // retval to get popped back into r0
      svc_args[0] = ret;
      break;
    }
    case 3: {
      yield();
      break;
    }
    case 4: {
      // Argument TID from r0 on stack
      task_t tid = (task_t)svc_args[0];
      TCB *task_copy = (TCB *)svc_args[1];
      ret = taskInfo(tid, task_copy);
      // retval to get popped back into r0
      svc_args[0] = ret;
      break;
    }
    case 5: {
      ret = getTID();
      // retval to get popped back into r0
      svc_args[0] = ret;
      break;
    }
    case 6: {
      ret = taskExit();
      svc_args[0] = ret;
      break;
    }
    case 7:{
      ret = mem_init();
      svc_args[0] = ret;
      break;
    }
    case 8:{
      // Argument size from r0 on stack
      size_t size = (size_t)svc_args[0];
      void *ptr = mem_alloc(size);
      // retval to get popped back into r0
      svc_args[0] = (unsigned int)ptr;
      break;
    }
    case 9: {
      // Argument ptr from r0 on stack
      void *ptr = (void *)svc_args[0];
      ret = mem_dealloc(ptr);
      // retval to get popped back into r0
      svc_args[0] = ret;
      break;
    }
    case 10: {
      size_t size = (size_t)svc_args[0];
      ret = mem_count_extfrag(size);
      svc_args[0] = ret;
      break;
    }
    case 12: {
        int deadline = (int)svc_args[0];
        task_t TID = (task_t)svc_args[1];
        ret = osSetDeadline(deadline, TID);
        // retval to get popped back into r0
        svc_args[0] = ret;
        break;
    }
    default: {
      break;
    }
  }
}
